require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'capybara'
require 'SitePrism'

Cucumber::Rake::Task.new(:features) do |t|
  t.profile = 'default'
end

task :default => :features
